import "./globals.css";
import { Navbar } from "@/components/Navbar";
import Modal from "@/components/Modal";

export const metadata = {
  title: "Trello Clone",
  description: "Generated by Alfonso Martín",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={"bg-[#F5F6F8]"}>
        <div
          className={
            "absolute top-0 left-0 w-full h-96 bg-gradient-to-br from-pink-400 to-[#0055D1] rounded-md filter blur-3xl opacity-50 z-0"
          }
        />
        <Navbar />

        <main className={"relative z-10"}>
          <Modal />
          {children}
        </main>
      </body>
    </html>
  );
}
